environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - yaml-example
pipelines:
  yamlpipe1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ysnoussi/sonar-ts-demo.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: -c npm install &amp;&amp; npm run build &amp;&amp; npm run test &amp;&amp; npm run cover &amp;&amp; npm run sonar